require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '18.0'
install! 'cocoapods', :deterministic_uuids => false

target 'CasasRVA' do
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
  # Update TOCropViewController to a newer version that supports iOS 15+
  pod 'TOCropViewController', '~> 2.6.1'
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    # Upcoming versions of React Native may rely on get_default_flags(), but
    # we make it explicit here to aid in the React Native upgrade process.
    :hermes_enabled => true,
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'CasasRVATests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      # Set `mac_catalyst_enabled` to `true` in order to apply patches
      # necessary for Mac Catalyst builds
      :mac_catalyst_enabled => false
    )
    
    # Fix deployment targets for all pods
    installer.pods_project.targets.each do |t|
      t.build_configurations.each do |c|
        c.build_settings['ENABLE_BITCODE'] = 'NO'
        c.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '18.0'
        # Fix Hermes dSYM generation
        if t.name == 'hermes-engine'
          c.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf-with-dsym'
          c.build_settings['GCC_GENERATE_DEBUGGING_SYMBOLS'] = 'YES'
        end
      end
    end
  end
end
